M48
; DRILL file {KiCad 8.0.5} date 2024-12-25T22:13:44-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-12-25T22:13:44-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X91.69Y-50.95
X91.69Y-115.771
X178.939Y-50.95
X178.939Y-115.771
M30
